config/routes.rb
Rails.application.routes.draw do
  resources :user_testimonials
  resources :custom_trips
  resources :customer_msgs
  resources :tours
  resources :booking_infos
  post 'checkout/create', to: 'checkout#create'
  resources :webhooks, only: [:create]
  # post 'webhooks/create', to: 'webhooks#create'
  # post 'create' => 'checkout#create', as: :checkout_create

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root :to => 'home#landing_page'
  # =========== error pages =========================
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match "/504", to: "errors#timed_out", via: :all
  match "/422", to: "errors#unacceptable", via: :all
  # ====================================================
  get 'user_dashboard' => 'home#user_dashboard', as: :user_dashboard  
  get 'admin_dashboard' => 'home#admin_dashboard', as: :admin_dashboard
  get 'profile' => 'home#profile', as: :profile
  get 'trips_page' => 'home#trips_page', as: :trips_page
  get 'media_page' => 'home#media_page', as: :media_page
  get 'booking_form' => 'home#booking_form', as: :booking_form
  get 'booking_form2' => 'home#booking_form2', as: :booking_form2
  post 'create_booking' => 'home#create_booking', as: :create_booking
  post 'create_msg' => 'home#create_msg', as: :create_msg
  get 'payment_form' => 'booking_infos#payment_form', as: :payment_form
  get 'book_form' => 'tours#book_form', as: :book_form
  get 'postpone_booking' => 'booking_infos#postpone_booking', as: :postpone_booking
  get 'booking_details' => 'home#booking_details', as: :booking_details
  get 'checkout_page' => 'home#checkout_page', as: :checkout_page
  get 'custom_trip_form' => 'home#custom_trip_form', as: :custom_trip_form
  post 'create_custom_trip' => 'home#create_custom_trip', as: :create_custom_trip
  get 'tos' => 'home#tos', as: :tos
  get 'testimonial_form' => 'home#testimonial_form', as: :testimonial_form
  post 'create_testimonial' => 'home#create_testimonial', as: :create_testimonial
  get 'privacy_policy' => 'home#privacy_policy', as: :privacy_policy
  get 'upcoming_trips_modal' => 'home#upcoming_trips_modal', as: :upcoming_trips_modal

  get 'success_page' => 'home#success_page', as: :success_page
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!, :except => [:landing_page,:booking_form,:privacy_policy, :success_page, :booking_form2, :booking_details, :create_booking, :custom_trip_form, :create_custom_trip, :tos, :testimonial_form] # :checkout_page,
    def landing_page
      if user_signed_in?
        if current_user.role_code == "client"
          @tours = Tour.where(active_status: true, del_status: false).order(start_date: :asc).limit(5)
          booking_infos = BookingInfo.where("user_id = ?", current_user.id)
          @pagy, @booking_infos = booking_infos.present? ? pagy(BookingInfo.where("user_id = ?", current_user.id).order(created_at: :desc) ) : pagy(BookingInfo.where("surname = ? AND othernames = ? AND email = ?",current_user.surname,current_user.othernames,current_user.email).order(created_at: :desc) )
        else
          @tours = Tour.where(active_status: true, del_status: false).order(start_date: :asc).limit(5)
          @pagy, @booking_infos = pagy(BookingInfo.all.order(created_at: :desc) )
        end
      else
        @tours = Tour.where(active_status: true, del_status: false).order(start_date: :asc).limit(5)
        logger.info "THE TOURS = #{@tours.inspect}"
        @customer_msg = CustomerMsg.new
      end
      @coordination_preference = [["Air and Ground","AG"],["Ground only","G"]]
      @hotel_type = [["5 Star","5 Star"],["4 Star","4 Star"],["3 Star","3 Star"]]
    end

    def upcoming_trips_modal
      @tours = Tour.where(active_status: true, del_status: false).order(start_date: :desc)
    end

    def checkout_page
      @tours = Tour.where('id = ?',params[:tour_id])[0]
      @booking = BookingInfo.where("tour_id=?",params[:tour_id])[0]
      @count = @booking.group_count
      logger.info "The booking form \n #{params[:tour_id].inspect}"
    end

    def booking_form
      @tours = Tour.where(active_status: true, del_status: false).order(title: :asc)
      @coordination_preference = [["Air and Ground","AG"],["Ground only","G"]]
      @hotel_type = [["5 Star","5 Star"],["4 Star","4 Star"],["3 Star","3 Star"]]
      @purpose_statement = [["Cultural visit","Cultural visit"],["Potential business","Potential business"],["Shopping","Shopping"],["Honeymoon","Honeymoon"]]
    end

    def booking_form2
      @tours = Tour.where(active_status: true, del_status: false).order(title: :asc)
      @coordination_preference = [["Air and Ground","AG"],["Ground only","G"]]
      @hotel_type = [["5 Star","5 Star"],["4 Star","4 Star"],["3 Star","3 Star"]]
      @purpose_statement = [["Cultural visit","Cultural visit"],["Potential business","Potential business"],["Shopping","Shopping"],["Honeymoon","Honeymoon"]]
    end

    def booking_details
      @tour = Tour.where("title = ? AND active_status = true AND del_status = false", params[:title])[0]
      logger.info"\n tour deets #{@tour.inspect}"
    end

    def testimonial_form
      @tours = Tour.where(active_status: true, del_status: false).order(title: :asc)
    end

    def create_testimonial
      @user_testimonial = UserTestimonial.new(booking_form_params)

      respond_to do |format|
        if @user_testimonial.valid?
          @user_testimonial =  UserTestimonial.new(fullname: booking_form_params[:fullname],
                                              testimonial: booking_form_params[:testimonial],
                                              tour_id: booking_form_params[:tour_title])
                                              logger.info "Testimonial form = #{@user_testimonial.inspect}"
          @user_testimonial.save(validate: false)
          format.html { redirect_to root_path, notice: "Your testimonial was successfully submitted" }
          format.json { render :show, status: :created, location: @user_testimonial }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @user_testimonial.errors, status: :unprocessable_entity }
        end
      end
    end

    def custom_trip_form
      @tours = Tour.all
      @coordination_preference = [["Air and Ground","AG"],["Ground only","G"]]
      @hotel_type = [["5 Star","5 Star"],["4 Star","4 Star"],["3 Star","3 Star"]]
      @purpose_statement = [["Cultural visit","Cultural visit"],["Potential business","Potential business"],["Shopping","Shopping"],["Honeymoon","Honeymoon"]]
    end

    def tos
    end

    def privacy_policy
    end

    def create_booking
        @booking_form_data = BookingInfo.new(booking_form_params)

        respond_to do |format|
          if @booking_form_data.valid?
            @booking_form_data =  BookingInfo.new(surname: booking_form_params[:surname],
            othernames: booking_form_params[:othernames],
            tour_id: booking_form_params[:tour_id],
            phone_number: booking_form_params[:phone_number],
            email: booking_form_params[:email],
            coordination_preference: booking_form_params[:coordination_preference],
            group_count: booking_form_params[:group_count],
            hotel_type: booking_form_params[:hotel_type],
            tour_duration: booking_form_params[:tour_duration],
            purpose_statement: "#{booking_form_params[:purpose_statement]}" + "  -  " +"#{booking_form_params[:comment]}",
            tos_agreement: booking_form_params[:tos_agreement])
            logger.info "Booking Info from form = #{@booking_form_data.inspect}"
            @booking_form_data.save(validate: false)
            BookingInfoMailer.with(booking_info: @booking_form_data).new_booking_info_email.deliver_later
            format.html { redirect_to checkout_page_path(tour_id: @booking_form_data.tour_id, booking_id:  @booking_form_data.id, count: @booking_form_data.group_count), notice: "Booking info was successfully created." }
            format.json { render :landing_page, status: :created, location: root_path }
          else
            logger.info "THE BOOKING ERROR = #{@booking_form_data.errors.messages}"
            format.js  render 'booking_form'
            format.json { render json: @booking_form_data.errors, status: :unprocessable_entity }
          end
        end
    end

    def success_page
    end

    def create_custom_trip
      @booking_form_data = CustomTrip.new(booking_form_params)

      respond_to do |format|
        if @booking_form_data.valid?
          @booking_form_data =  CustomTrip.new(surname: booking_form_params[:surname],
          othernames: booking_form_params[:othernames],
          destination: booking_form_params[:destination],
          phone_number: booking_form_params[:phone_number],
          email: booking_form_params[:email],
          coordination_preference: booking_form_params[:coordination_preference],
          group_count: booking_form_params[:group_count],
          hotel_type: booking_form_params[:hotel_type],
          trip_duration: booking_form_params[:trip_duration],
          purpose_statement: booking_form_params[:purpose_statement],
          comment: booking_form_params[:comment],
          tos_agreement: booking_form_params[:tos_agreement])
          logger.info "Booking Info from form = #{@booking_form_data.inspect}"
          @booking_form_data.save(validate: false)
          BookingInfoMailer.with(booking_info: @booking_form_data, marker: "custom").new_booking_info_email.deliver_later
          
          flash.now[:notice]="Your customized trip request was created successfully, we will reachout to you on the email you provided"
          format.html { redirect_to root_path, notice: "Your customized trip request was created successfully, we will reachout to you on the email you provided" }
          format.json { render :landing_page, status: :created, location: root_path }
        else
          logger.info "THE BOOKING ERROR = #{@booking_form_data.errors.messages}"
          format.js  render 'custom_trip'
          format.json { render json: @booking_form_data.errors, status: :unprocessable_entity }
        end
      end
    end


    def create_msg
      @customer_msg = CustomerMsg.new(customer_msg_params)

      respond_to do |format|
        if @customer_msg.save
          format.html { redirect_to @customer_msg, notice: "Customer msg was successfully created." }
          format.json { render :show, status: :created, location: @customer_msg }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @customer_msg.errors, status: :unprocessable_entity }
        end
      end
    end

    def user_dashboard
      @tours = Tour.where("active_status = true AND del_status = false").limit(5)
      logger.info "THE TOURS = #{@tours.inspect}"
      @coordination_preference = [["Air and Ground","AG"],["Ground only","G"]]
      @hotel_type = [["5 Star","5 Star"],["4 Star","4 Star"],["3 Star","3 Star"]]

      @customer_msg = CustomerMsg.new
    end

    def admin_dashboard
    end

    def profile
    end

    def trips_page
    end

    def media_page
    end

    # Only allow a list of trusted parameters through.
    def booking_form_params
        params.require(:booking_form).permit(:tos_agreement ,:destination, :trip_duration, :comment, :tour_id, :surname, :othernames, :full_name, :phone_number, :email, :coordination_preference, :group_count, :hotel_type, :tour_duration, :purpose_statement)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_carousel.html.erb
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active overlay">
            <img src="<%= asset_pack_path 'media/images/image4.jpg' %>" width="100%" height="540px" alt="HBCU Africa">
            <div class="carousel-caption d-none d-md-block">
                <p class="carousel-bold-textt">
                    HBCU Homecoming 2022: 100,000 Strong Africa Conference
                </p>
                <p class="carousel-mini-textt">
                   24 MAY, 2022 - 30 MAY, 2022
                </p>
                <br>
                <%= link_to 'Travel with us', booking_form_path, class:"cta-btn-light shadow-lg",style:"color: #101010 !important;background-color: #FBC71D !important;", remote:true%>

            </div>
        </div>
        <div class="carousel-item overlay">
            <img src="<%= asset_pack_path 'media/images/5.jpg' %>" width="100%" height="540px" alt="Tz beach">
            <div class="carousel-caption d-none d-md-block">
                <p class="carousel-bold-textt">
                    Sanbrafie Tanzania Summer, 2023
                </p>
                <p class="carousel-mini-textt">
                    22 JUN, 2023 - 29 JUN, 2023
                </p>
                <br>
                <%= link_to 'Travel with us', booking_form_path, class:"cta-btn-light shadow-lg",style:"color: #101010 !important;background-color: #FBC71D !important;", remote:true%>

            </div>
        </div>
        <div class="carousel-item overlay">
            <img src="<%= asset_pack_path 'media/images/ghdec.jpg' %>" width="100%" height="540px" alt="December in Ghana">
            <div class="carousel-caption d-none d-md-block">
                <p class="carousel-bold-textt">
                   Ghana December, 2022
                </p>
                <p class="carousel-mini-textt">
                    23 DEC, 2022 - 01 JAN, 2023
                </p>
                <br>
                <%= link_to 'Travel with us', booking_form_path, class:"cta-btn-light shadow-lg",style:"color: #101010 !important;background-color: #FBC71D !important;", remote:true%>
            </div>
        </div>
        <div class="carousel-item">
            <img src="<%= asset_pack_path 'media/images/logotext.png' %>" width="100%" height="540px" alt=" demo instructions">
            <div class="carousel-caption d-none d-md-block">
                
            </div>
        </div>
    </div>
</div>


<style>

.carousel-bold-textt{
  color: #fafafa ;
  font-size:46px !important;
  line-height: 105% !important;
  font-family: 'Montserrat';
  font-weight: 600;
}
.carousel-mini-textt{
  color: #fafafa !important;
  font-family: 'Open sans' !important;
  font-size: 32px !important;
  line-height:38px!important;
  font-weight: 400 !important;
  opacity:0.8;
}

.carousel-caption{
  text-align: left !important;
  margin-left: -100px;
  position: absolute;
  top: 45% !important;
  z-index: 100000000;
  // -ms-transform: translateY(-20%);
  // transform: translateY(-20%);
}
</style>

app/views/home/_custom_trip_form.html.erb
 <div id="custom-mod" class="w3-modal w3-animate-opacity" style="display: block; z-index: 4; margin-top: 50px;">
    <div class="w3-modal-content w3-card-4 " style="width: 540px; padding-bottom: 60px" >
      <div class="d-flex justify-content-end" style="padding:10px;">
        <span onclick="document.getElementById('custom-mod').style.display='none'"
            class="btn btn-lg btn-light">&times;</span>
      </div>
      <br>
      <div class="w3-container">
        <%#= simple_form_for(@custom_trip) do |f| %>
        <%= simple_form_for :booking_form, url: create_custom_trip_path, :method =>'post' ,html: { class: 'form-horizontal' } do |f| %>
            <form>
                <div class="form-inputs my-form-margin">
                    <div class="col-sm-12">
                     
                        <div  class="mb-3">
                            <%= f.input :destination, input_html:{class:"form-control-lg sanbrafie-input", required: true}, label:"Where would you like to go?" %>   
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-6">
                                <%= f.input :surname, input_html:{class:"form-control-lg sanbrafie-input", required: true}, label:"Lastname" %>
                            </div>
                            <div class="col-sm-6">
                                <%= f.input :othernames, input_html:{class:"form-control-lg sanbrafie-input", required: true}, label:"Firstname" %>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-6">
                                <%= f.input :phone_number, input_html:{class:"form-control-lg sanbrafie-input", required: true} %>
                            </div>
                            <div class="col-sm-6">
                                <%= f.input :email, input_html:{class:"form-control-lg sanbrafie-input", required: true} %>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-6">
                                <%= f.input :coordination_preference, collection: @coordination_preference, label_method: :first, value_method: :last, input_html:{class:"form-control-lg form-select sanbrafie-input", required: true} %>
                            </div>
                            <div class="col-sm-6">
                                <%= f.input :group_count, input_html:{class:"form-control-lg sanbrafie-input", required: true}, label:"Number of people" %>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-6">
                                <%= f.input :hotel_type, collection: @hotel_type, label_method: :first, value_method: :last, input_html:{class:"form-control-lg form-select sanbrafie-input", required: true}, label:"What type of hotel would you like to stay at?" %>
                            </div>
                            <div class="col-sm-6">
                                <%= f.input :trip_duration, input_html:{class:"form-control-lg sanbrafie-input", required: true}, label:"How long do you want to stay?" %>
                            </div>
                        </div>
                        <div  class="mb-3">
                            <%= f.input :purpose_statement, collection: @purpose_statement, label_method: :first, value_method: :last, input_html:{class:"form-control-lg form-select sanbrafie-input", required: true} %>
                            <br>
                            <%= f.input :comment, as: :text, input_html:{class:"form-control-lg sanbrafie-input"}, placeholder:"Add a little detail to your purpose statement",label:false %>
                        </div>
                        <div  class="row mb-3">
                            <div class="col-1" style="margin-top: 1px !important; ">
                                <%= f.input :tos_agreement, wrapper: :vertical_boolean, as: :boolean , label: false, required: true %>
                            </div>
                            <div class="col-11">
                                <p>I agree to the <%= link_to "Terms of service",tos_path,remote: true %></p>
                            </div>
                        </div>
                        <br>
                        <div class="d-grid gap-2">
                            <%= f.submit "Customize your trip", class: "btn btn-lg btn-dark" %>
                        </div>
                    </div>
                </div>
            </form>
        <% end %>
      </div>
    </div>
</div>

<style>
    .sanbrafie-input{
        background-color:#f2f2f2  !important;
        border:none !important;
        border-radius: 0px !important;
    }
    .my-form-margin{
        padding: 0 40px;
    }
</style>

app/views/home/_dash.html.erb
<div class="book booking-edit"></div>
<div class="booking-details"></div>
<div class="custom-trip"></div>
<div class="tos-form"></div>
<div id="trips"></div>
<div class="row" style="margin-top: 20px !important;">
    <div class="col-sm-8 booking-table-section">
    <div style="padding: 40px 0 40px 30px; border-bottom: 0.3px #dedede solid; background-color: #f5f5f7; margin: 0 -10px;">
        <h3 class="my-h3">Hello <%= current_user.username.capitalize %></h3>
    </div>
    <br>
    <div id="upcoming-trips-btn">
        <div class="d-grid gap-2" style="margin: 0 auto; width:94%;">
            <%= link_to 'Upcoming trips', upcoming_trips_modal_path, class:"btn btn-dark btn-lg",remote:true%>
        </div>
    </div>
    <br>
    <div class="booking-table" style="margin: 0 auto; width:94%;">       
        <div class="wrapper ">
            <div class="page-header">
                <% if current_user.role_code == "admin"%>
                    <h3>View All Customer Booking History</h3>
                <% else %>
                    <h3>View Your Booking History</h3>
                <% end %>
            </div>
            <br>

            <div class="table-responsive shadow-sm" style="padding: 10px;border: 0.3px solid #dedede;">
                <table class="table table-hover table-lg">
                    <thead style="height: 50px; border-top: 1px solid #000; background-color: #f5f5f7;">
                    <tr>
                        <th>#</th>
                        <th>Trip</th>
                        <th>Coordination</th>
                        <th>No. of people</th>
                        <%# <th>Hotel</th> %>
                        <th>Duration</th>
                        <th colspan="2"></th>
                    </tr>
                    </thead>
                    <tbody>
                    <% @booking_infos.each_with_index do |booking_info,index| %>
                    <% @tour = Tour.where("id = ?",booking_info.tour_id)[0]%>
                        <tr>
                        <td><%= index+1 %></td>
                        <td><%= @tour.title if !@tour.nil?%></td>
                        <td><%= booking_info.coordination_preference %></td>
                        <td><%= booking_info.group_count %></td>
                        <!--<td><%#= booking_info.hotel_type %></td>-->
                        <td><%= booking_info.tour_duration %></td>
                        
                        <% if booking_info.payment_status %>
                            
                        <% else %>
                            <td>
                                <%= link_to checkout_page_path(tour_id: booking_info.tour_id, count: booking_info.group_count), class:"btn btn-dark", style:"width:80px;" do %>
                                    Pay
                                <% end %>
                            </td>
                        <% end %>
                        
                        <td>
                            <% if booking_info.status == 'postponed'%>
                                <%= link_to edit_booking_info_path(booking_info, marker:"postponed"),remote:true, class:"btn btn-secondary" do %>
                                    Postponed
                                <% end %>
                            <% else %>
                                <%= link_to edit_booking_info_path(booking_info),remote:true, class:"btn btn-outline-dark" do %>
                                    Postpone trip
                                <% end %>
                            <% end %>
                        </td>
                        <%# <td><button class="btn btn-dark"><i class="fas fa-upload"></i></button></td> %>
                        </tr>
                    <% end %>
                    </tbody>
                    <div class="items-count">
                        No. of records: 
                        <%= link_to_unless_current '10',  root_path(items: 10), class:"item-cnt btn btn-sm btn-outline-dark"%>
                        <%= link_to_unless_current '20',  root_path(items: 20), class:"item-cnt btn btn-sm btn-outline-dark"%>
                        <%= link_to_unless_current '50',  root_path(items: 50), class:"item-cnt btn btn-sm btn-outline-dark"%>
                        <%= link_to_unless_current '100',  root_path(items: 100), class:"item-cnt btn btn-sm btn-outline-dark"%>
                    </div>
                </table>
                <%== pagy_bootstrap_nav(@pagy) %>
            </div>
        </div>
    </div>

    </div> 
    <div class="col-sm-4 shadow-sm" id="upcoming-trips-section" style="background-color:#f5f5f7; padding: 20px 10px; border-left: 0.3px solid #dedede;">
        <div class="row" >
            <div class="d-grid gap-2">
                <h2 class="text-center" style="margin-bottom:20px; font-family: 'Montserrat' !important; font-weight: 700;">Upcoming Trips</h2>
                <% if current_user.role_code == "admin"%>
                    <%= link_to new_tour_path, class:"btn btn-lg btn-dark " do %>
                        Add a new trip
                    <% end %>
                <% end %>
                <hr>
            </div>
            <br>
            <hr>
        </div>
        <div class="table-responsive">
            <table class="table table-hover table-bordered" style="display: block; height: 100vh; overflow-y: scroll;">          
                <tbody>
                    <% @tours.each_with_index do |tour, index| %>
                        <tr>
                            <td>
                                <div class="">
                                    <%# <a href="/tours" > %>
                                        <% if tour.image.attached? %>
                                            <img src="<%= cloudinary_url(tour.image.key, options = {}) %>" alt=" demo instructions" class="tl2"> 
                                            <%#= cl_image_tag(@user.avatar.key, height:150px, width:150px, crop: :scale) %>
                                            <%#= cloudinary_url(tour.image.key, options = {}) %>
                                        <% else %>
                                            <img src="<%= asset_pack_path 'media/images/placeholder.png' %>" alt="Image not available" class="tl2">
                                        <% end %>
                                    <%# </a> %>
                                </div>
                            </td>
                            <td class="align-top">
                                <!-- <b><%#= tour.tour_id %></b><br> -->
                                <span class="text-4"><%= tour.title %></span><br>
                                <%#= tour.start_date.strftime("%m-%d-%Y") if !tour.start_date.nil?%>
                                <% date = tour.start_date %>
                                <span class="text-3 font-weight-300"><%=  date.to_date.strftime("%d") if !date.nil?%></span>
                                <span class="text-1 font-weight-300 text-uppercase"><%= date.to_date.strftime("%b") if !date.nil?%>,
                                    <%=  date.to_date.strftime("%Y") if !date.nil? %>
                                </span>
                                 -to- 
                                <% date = tour.end_date %>
                                <span class="text-3 font-weight-300"><%=  date.to_date.strftime("%d") if !date.nil?%></span>
                                <span class="text-1 font-weight-300 text-uppercase"><%= date.to_date.strftime("%b") if !date.nil?%>,
                                    <%=  date.to_date.strftime("%Y") if !date.nil? %>
                                </span>
                                <br>
                                <span class="text-3 font-weight-300 text-uppercase">$ <%= tour.price/100 if !tour.price.nil?%></span>
                                <br>
                                <%= link_to "Itinerary",booking_details_path(id: tour.id),remote: true, class:"btn btn-link" %>
                                <br>
                                <div class="row">
                                    <div class="col-sm-6 d-grid gap-2">
                                        <%= link_to "Book Trip", book_form_path(tour_id: tour.id), class:"btn btn-md btn-dark", remote: true%>
                                    </div>
                                    <div class="col-sm-6 d-grid gap-2">
                                        <% if current_user.role_code == 'admin'%>
                                            <%= link_to edit_tour_path(tour), class:"btn btn-md btn-secondary" do %>
                                                <i class="fas fa-edit"></i> Edit
                                            <% end %>
                                        <% end %>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

<style>
    .item-cnt{
        margin: 10px 5px;
    }
    .tl2{
    margin: 5px;
    height:150px !important;
    width:150px !important;
    border-radius: 5px;
    }

    .tl2:hover{
    height:153px !important;
    width:153px !important;
    }
    .my-h3{
        font-weight: 400; 
        font-family: 'Poppins';
    }
    .page-topic{
    padding: 20px 0 16px 0;
    background-color: #f5f5f7 !important;
    color:#161616 !important;
    border-bottom:1px solid #ececec;
    }

    .page-link{
        color: #000 !important;
    }

    .page-item.active .page-link{
        background-color: #1c1f23 !important;
        border-color: #1c1f23 !important;
        color: #fff !important;
    }
</style>

app/views/home/_login_form.html.erb
    <div id="login" class="w3-modal w3-animate-opacity" style="display: block"> 
        <div class="modal-dialog modal-dialog-scrollable" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <p id="notice"><%= notice %></p>
                    <%# <h5 class="modal-title" id="exampleModalLabel"> Notes </h5> %>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span onclick="document.getElementById('login').style.display='none'"
                        >&times;</span>
                    </button>
                </div>
                <div class="modal-body">         
                          
                    <h2>Log in</h2>

                    <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
                    <div class="form-inputs">
                        <%= f.input :email,
                                    required: false,
                                    autofocus: true,
                                    input_html: { autocomplete: "email" } %>
                        <%= f.input :password,
                                    required: false,
                                    input_html: { autocomplete: "current-password" } %>
                        <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
                    </div>

                    <div class="form-actions">
                        <%= f.button :submit, "Log in" %>
                    </div>
                    <% end %>

                    <%= render "devise/shared/links" %>

                </div>
                <div class="modal-footer">
                    <span onclick="document.getElementById('login').style.display='none'"
                        class="btn btn-md btn-secondary btn-block" >Close</span>

                </div>
            </div>
        </div>
    </div>