config/routes.rb
Rails.application.routes.draw do
  resources :user_testimonials
  resources :custom_trips
  resources :customer_msgs
  resources :tours
  resources :booking_infos
  post 'checkout/create', to: 'checkout#create'
  resources :webhooks, only: [:create]
  # post 'webhooks/create', to: 'webhooks#create'
  # post 'create' => 'checkout#create', as: :checkout_create

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root :to => 'home#landing_page'
  # =========== error pages =========================
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match "/504", to: "errors#timed_out", via: :all
  match "/422", to: "errors#unacceptable", via: :all
  # ====================================================
  get 'user_dashboard' => 'home#user_dashboard', as: :user_dashboard  
  get 'admin_dashboard' => 'home#admin_dashboard', as: :admin_dashboard
  get 'profile' => 'home#profile', as: :profile
  get 'trips_page' => 'home#trips_page', as: :trips_page
  get 'media_page' => 'home#media_page', as: :media_page
  get 'booking_form' => 'home#booking_form', as: :booking_form
  get 'booking_form2' => 'home#booking_form2', as: :booking_form2
  post 'create_booking' => 'home#create_booking', as: :create_booking
  post 'create_msg' => 'home#create_msg', as: :create_msg
  get 'payment_form' => 'booking_infos#payment_form', as: :payment_form
  get 'book_form' => 'tours#book_form', as: :book_form
  get 'postpone_booking' => 'booking_infos#postpone_booking', as: :postpone_booking
  get 'booking_details' => 'home#booking_details', as: :booking_details
  get 'checkout_page' => 'home#checkout_page', as: :checkout_page
  get 'custom_trip_form' => 'home#custom_trip_form', as: :custom_trip_form
  post 'create_custom_trip' => 'home#create_custom_trip', as: :create_custom_trip
  get 'tos' => 'home#tos', as: :tos
  get 'testimonial_form' => 'home#testimonial_form', as: :testimonial_form
  post 'create_testimonial' => 'home#create_testimonial', as: :create_testimonial
  get 'privacy_policy' => 'home#privacy_policy', as: :privacy_policy
  get 'upcoming_trips_modal' => 'home#upcoming_trips_modal', as: :upcoming_trips_modal

  get 'success_page' => 'home#success_page', as: :success_page
end

app/models/tour.rb
class Tour < ApplicationRecord
    has_one_attached :image
    
    validates :title, presence: true
    # validates :price, numeric: true
    validates :start_date, presence: true
    validates :end_date, presence: true

    def self.gen_assigned_id
        sql = "select nextval('tour_seq')"
        val = ActiveRecord::Base.connection.execute(sql)
        val = val.values[0][0]
        val = val.to_s.rjust(5,'0')
        logger.info "Tour ID, #{val}"
        val
    end

    def self.check_seq_code

        assigned_id = loop do
            assigned_id=gen_assigned_id
            break assigned_id unless Tour.exists?(tour_id: assigned_id)
        end

        return assigned_id
    end

    def self.update_last_but_one(table,id_field,id)
        sql = "UPDATE #{table} SET active_status = false, del_status = true   WHERE id = (SELECT id FROM #{table} WHERE #{id_field} = '#{id}' AND active_status = true AND del_status  = false order by id asc LIMIT 1)"
        val = ActiveRecord::Base.connection.execute(sql)
        # logger.info "VALUE: #{val.inspect}"
    end

     # create stripe product and assign to this product
    after_create do
        trip = Stripe::Product.create(name: title)
        price = Stripe::Price.create(product: trip, unit_amount: self.price, currency: self.currency)
        update(stripe_product_id: trip.id, stripe_price_id: price.id)
    end

    # after_update do
    #     trip = Stripe::Product.create(name: title)
    #     price = Stripe::Price.create(product: trip, unit_amount: self.price, currency: self.currency)
    #     update(stripe_product_id: trip.id, stripe_price_id: price.id)
    # end

    # stripe keeps products and prices separately. 
    # updating local prices would require to update or create stripe prices.
    # this is all additional complexity.
    # better just create new products.

    # after_update :create_and_assign_new_stripe_price, if: :saved_change_to_price?
    # after_update :create_and_assign_new_stripe_price, if: :saved_change_to_currency?

    # def create_and_assign_new_stripe_price
    #   price = Stripe::Price.create(product: self.stripe_product_id, unit_amount: self.price, currency: self.currency)
    #   update(stripe_price_id: price.id)
    # end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: %i[ show edit update destroy ]

  # GET /tours or /tours.json
  def index
    @tours = Tour.all
  end

  def book_form
    @coordination_preference = [["Air and Ground","AG"],["Ground only","G"]]
    @hotel_type = [["5 Star","5 Star"],["4 Star","4 Star"],["3 Star","3 Star"]]
    @purpose_statement = [["Cultural visit","Cultural visit"],["Potential business","Potential business"],["Shopping","Shopping"],["Honeymoon","Honeymoon"]]

  end

  # GET /tours/1 or /tours/1.json
  def show
  end

  # GET /tours/new
  def new
    @tour = Tour.new
  end

  # GET /tours/1/edit
  def edit
  end

  # POST /tours or /tours.json
  def create
    @tour = Tour.new(tour_params)
    @tour.tour_id = Tour.check_seq_code

    respond_to do |format|
      if @tour.save
        format.html { redirect_to root_path, notice: "Trip was successfully created." }
        format.json { render :show, status: :created, location: @tour }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tours/1 or /tours/1.json
  def update
    @trip_params = Tour.new(tour_params)
    @trip = Tour.where("id=? AND active_status = true AND del_status=false",params[:id]).order(created_at: :desc).first

    respond_to do |format|
      if  @trip_params.valid?
        if @trip.tour_id.nil?
          @trip.tour_id = Tour.check_seq_code
        else
          logger.info "tour id is intact"
        end
        @new_trip_params = Tour.new(title: tour_params[:title], 
                                    price: tour_params[:price], 
                                    currency: tour_params[:currency], 
                                    description: tour_params[:description], 
                                    start_date: tour_params[:start_date], 
                                    end_date: tour_params[:end_date], 
                                    image: tour_params[:image],
                                    tour_id: @trip.tour_id)
        @new_trip_params.save(validate: false)

        Tour.update_last_but_one('tours','tour_id',@trip.tour_id)

        format.html { redirect_to root_path, notice: "Trip was successfully updated." }
        format.json { render :show, status: :ok, location: @tour }
      else
        @title = tour_param[:title]
        @price = tour_param[:price]
        @currency = tour_param[:currency]
        @description = tour_param[:description]
        @start_date = tour_param[:start_date]
        @end_date = tour_param[:end_date]
        @start = tour_param[:active_start_date]
        @image = tour_param[:image]
        @tour_id = tour_param[:tour_id]

        @tour.update(tour_param)
        logger.info "ERRORS == #{@trip_params.errors.messages.inspect}"
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end






    # respond_to do |format|
    #   if @tour.update(tour_params)
    #     format.html { redirect_to root_path, notice: "Trip was successfully updated." }
    #     format.json { render :show, status: :ok, location: @tour }
    #   else
    #     format.html { render :edit, status: :unprocessable_entity }
    #     format.json { render json: @tour.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /tours/1 or /tours/1.json
  def destroy
    @tour.destroy
    respond_to do |format|
      format.html { redirect_to tours_url, notice: "Trip was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tour_params
      params.require(:tour).permit(:tour_id, :title, :price, :currency, :stripe_product_id, :stripe_price_id, :description, :start_date, :end_date, :image, :sales_count)
    end
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/tours/_booking_form.html.erb
 <div id="air-mod" class="w3-modal w3-animate-opacity" style="display: block; margin-top: 50px;">
    <div class="w3-modal-content w3-card-4 " style="width: 540px; padding-bottom: 60px" >
      <div class="d-flex justify-content-end" style="padding: 10px;">
        <span onclick="document.getElementById('air-mod').style.display='none'"
            class="btn btn-lg btn-light">&times;</span>
      </div>
      <br>
      <div class="w3-container">
        <%= simple_form_for :booking_form, url: create_booking_path, :method =>'post' ,html: { class: 'form-horizontal' } do |f| %>
            <form>
                <div class="form-inputs my-form-margin">
                    <div class="col-sm-12">
                        <div class="d-grid gap-2">
                            <!--<span onclick="document.getElementById('air-mod').style.display='none'">-->
                                <%= link_to "Customize your trip", custom_trip_form_path, class:"btn btn-lg btn-danger", remote: true %>
                            <!--</span>-->
                        </div>
                        <br>
                        <div class="text-center">
                            <b><p>-- OR --</p></b>
                        </div>
                        <br>
                        <div  class="mb-3">
                            <%= f.input :tour_id, input_html:{value:params[:tour_id],class:"form-control-lg sanbrafie-input "}, as: :hidden %>   
                        </div>
                        <div class="row mb-3">
                            <div class="col">
                                <%= f.input :surname, input_html:{value: current_user.surname, class:"form-control-lg sanbrafie-input",required:true} %>
                            </div>
                            <div class="col">
                                <%= f.input :othernames, input_html:{value: current_user.othernames, class:"form-control-lg sanbrafie-input", required:true} %>
                            </div>
                        </div>
                        <div class=" mb-3">
                                <%= f.input :phone_number, input_html:{class:"form-control-lg sanbrafie-input"} %>
                                <%= f.input :user_id, input_html:{value: current_user.id,class:"form-control-lg sanbrafie-input"},as: :hidden %>
                                <%= f.input :user_uid, input_html:{value: current_user.uid,class:"form-control-lg sanbrafie-input"},as: :hidden %>
                                <%= f.input :email, input_html:{value: current_user.email,class:"form-control-lg sanbrafie-input"},as: :hidden %>
                                <%= f.input :status, input_html:{value: "active",class:"form-control-lg sanbrafie-input"},as: :hidden %>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-6">
                                <%= f.input :coordination_preference, collection: @coordination_preference, label_method: :first, value_method: :last, input_html:{class:"form-control-lg form-select sanbrafie-input", required: true} %>
                            </div>
                            <div class="col-sm-6">
                                <%= f.input :group_count, input_html:{class:"form-control-lg sanbrafie-input", required: true}, label:"Number of people" %>
                            </div>
                        </div>
                        <div  class="mb-3">
                            <%= f.input :purpose_statement, collection: @purpose_statement, label_method: :first, value_method: :last, input_html:{class:"form-control-lg form-select sanbrafie-input", required: true} %>
                            <br>
                            <%= f.input :comment, as: :text, input_html:{class:"form-control-lg sanbrafie-input"}, placeholder:"Add a little detail to your purpose statement",label:false, required: false %>
                        </div>

                        <div  class="row mb-3">
                            <div class="col-1" style="margin-top: 1px !important; ">
                                <%= f.input :tos_agreement, wrapper: :vertical_boolean, as: :boolean , label: false %>
                            </div>
                            <div class="col-11">
                                <p>I agree to the <%= link_to "Terms of service",tos_path,remote: true %></p>
                            </div>
                        </div>

                        <p class="text-danger" style="font-size: 16px; font-weight: 500;">Please note that the price is based on double occupancy.</p>
    
                        <br>
    
                        <br>
                        <div class="d-grid gap-2">
                            <%= f.submit "Book a tour", class: "btn btn-lg btn-dark" %>
                        </div>
                    </div>
                </div>
            </form>
        <% end %>
      </div>
    </div>
</div>

<style>
.w3-modal{
    z-index: 999 !important;
}
    .sanbrafie-input{
        background-color:#f2f2f2  !important;
        border:none !important;
        border-radius: 0px !important;
    }
    .my-form-margin{
        padding: 0 40px;
    }
</style>

app/views/tours/_edit.html.erb
<div class="row d-flex justify-content-center"> 
  <div class="col-5 " style="background-color:#dfe6e9; padding: 50px; ">
    <div class="log-form-margin">
      <%= simple_form_for(@tour) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="form-inputs">
          <%#= f.input :tour_id %>
          <%= f.input :title %>
          <%#= f.input :description %>
          <%= f.input :description, as: :ckeditor, input_html: { ckeditor: { toolbar: 'Full' } } %>
          <%= f.input :price, input_html:{},hint:"Price is in cents, please add 2 extra zeros(00) to your intended price" %><br>
          <%= f.input :currency, input_html:{value:"usd"}, as: :hidden %>
          <div class="row">
              <div class="col-md-6">
                <%= f.input :start_date, :id => "datepicker",  as: :date, html5: true, class:"input-group date", boolean_style: :inline, 
                input_html: {style: "width: 100%", data: {behaviour: 'datepicker', provide: 'datepicker'}, autocomplete: "off"}, label:"Start Date" %>
              </div>
              <div class="col-md-6">
                <%= f.input :end_date, :id => "datepicker",  as: :date, html5: true, class:"input-group date", boolean_style: :inline, 
                input_html: {style: "width: 100%", data: {behaviour: 'datepicker', provide: 'datepicker'}, autocomplete: "off"}, label:"Expiry Date" %>
              </div>
            </div>
            <br>
          <%= f.file_field :image, id: "avatar-upload" %>
          <br><br>
          <img id="img_prev" width=200 height=200 src="#" alt="your image" class="img-thumbnail hidden"/>
          
        </div>
        <br><br>
        <div class="form-actions">
          <%= link_to 'Back', root_path,class:"btn btn-lg btn-outline-dark"%>
          <%= f.button :submit ,class:"btn btn-lg btn-dark" %>
          
        </div>
      <% end %>
    </div>
  </div>
</div>


<script>
  $(function() {
				function readURL(input) {
					if (input.files && input.files[0]) {
						var reader = new FileReader();

						reader.onload = function (e) {
							$('#img_prev').attr('src', e.target.result);
						}
						reader.readAsDataURL(input.files[0]);
					}
				}

				$("#avatar-upload").change(function(){
					$('#img_prev').removeClass('hidden');
					readURL(this);
				});
			});


</script>

app/views/tours/_form.html.erb
<div class="row d-flex justify-content-center"> 
  <div class="col-5 " style="background-color:#dfe6e9; padding: 50px; ">
    <div class="log-form-margin">
      <%= simple_form_for(@tour) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="form-inputs">
          <%#= f.input :tour_id %>
          <%= f.input :title %>
          <%#= f.input :description %>
          <%= f.input :description, as: :ckeditor, input_html: { ckeditor: { toolbar: 'Full' } } %>
          <%= f.input :price, input_html:{},hint:"Price is in cents, please add 2 extra zeros(00) to your intended price" %><br>
          <%= f.input :currency, input_html:{value:"usd"}, as: :hidden %>
          <div class="row">
              <div class="col-md-6">
                <%= f.input :start_date, :id => "datepicker",  as: :date, html5: true, class:"input-group date", boolean_style: :inline, 
                input_html: {style: "width: 100%", data: {behaviour: 'datepicker', provide: 'datepicker'}, autocomplete: "off"}, label:"Start Date" %>
              </div>
              <div class="col-md-6">
                <%= f.input :end_date, :id => "datepicker",  as: :date, html5: true, class:"input-group date", boolean_style: :inline, 
                input_html: {style: "width: 100%", data: {behaviour: 'datepicker', provide: 'datepicker'}, autocomplete: "off"}, label:"Expiry Date" %>
              </div>
            </div>
            <br>
          <%= f.file_field :image, id: "avatar-upload" %>
          <br><br>
          <img id="img_prev" width=200 height=200 src="#" alt="your image" class="img-thumbnail hidden"/>
          
        </div>
        <br><br>
        <div class="form-actions">
          <%= link_to 'Back', root_path,class:"btn btn-lg btn-outline-dark"%>
          <%= f.button :submit ,class:"btn btn-lg btn-dark" %>
          
        </div>
      <% end %>
    </div>
  </div>
</div>


<script>
  $(function() {
				function readURL(input) {
					if (input.files && input.files[0]) {
						var reader = new FileReader();

						reader.onload = function (e) {
							$('#img_prev').attr('src', e.target.result);
						}
						reader.readAsDataURL(input.files[0]);
					}
				}

				$("#avatar-upload").change(function(){
					$('#img_prev').removeClass('hidden');
					readURL(this);
				});
			});


</script>

app/views/tours/book_form.js.erb
$('.book').html("<%= escape_javascript(render 'booking_form')%>")

app/views/tours/edit.html.erb
<div class="row d-flex justify-content-center text-center">
    <div><h1>Editing Tour</h1></div>
</div>
<%= render 'edit', tour: @tour %>

app/views/tours/index.html.erb
<div class="page-topic text-center">
    <h2> tours </h2>
</div>
<div class="book"></div>
<div class="my-content"> 
    <div class="shadow-box-no-border">
        <div class="manual-breadcrumb">
        <a class="btn-md btn btn-light" href="/">Home</a>  |  <a class="btn-md btn btn-light" href="/tours">Tours</a> 
        <!--    <%# if params[:path] == 'root_path' %>
                <a class="btn-sm btn btn-link" href="/">Home</a>
            <%# else %>
                <%#= link_to "#{params[:page_name]}", params[:path], class:"btn-sm btn btn-link" %>
            <%# end %> / <a class="btn-sm btn btn-link" href="/tours">Tours</a> -->
        </div>
        <hr/>
        <% if current_user.role_code == 'admin' %>
            <div class="d-flex justify-content-end">     
                <%= link_to new_tour_path, class:"btn btn-dark " do %>
                    New Tour
                <% end %>
            </div>
         <% end %>
        <div class="row">
           
            <div class="col">
                <div class="table-responsive">
                    <table class="table table-hover">          
                        <tbody>
                            <% @tours.each_with_index do |tour, index| %>
                                <tr>
                                    <td>
                                        <div class="">
                                            <a href="/tours">
                                                <% if tour.image.attached? %>
                                                    <img src="<%= url_for(tour.image) %>" height="280px" width="280px" alt=" demo instructions" class="tl">
                                                <% else %>
                                                    <p class="text-center">Image not available</p>
                                                <% end %>
                                            </a>
                                        </div>
                                    </td>
                                    <td>
                                        <%= tour.tour_id %><br>
                                        <%= tour.title %><br>
                                        <%= tour.stripe_product_id %><br>
                                        <%= tour.stripe_price_id %><br>
                                        <%= tour.start_date %><br>
                                        <%= tour.end_date %><br><br>
                                        <%= tour.sales_count %><br><br>
                                        <%= link_to "Book", book_form_path(tour_id: tour.id), class:"btn btn-md btn-dark", remote: true%>
                                        <% if current_user.role_code == 'admin'%>
                                            <%= link_to edit_tour_path(tour), class:"btn btn-md btn-secondary" do %>
                                                <i class="fa fa-edit"></i> Edit
                                            <% end %>
                                        <% end %>
                                    </td>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col">
            
            </div>
        </div>
        
    </div>
</div>

app/views/tours/new.html.erb
<div class="row d-flex justify-content-center text-center">
    <div><h1>Create a Tour</h1></div>
</div>
<%= render 'form', tour: @tour %>

app/views/tours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tour:</strong>
  <%= @tour.tour_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @tour.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tour.description %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @tour.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @tour.end_date %>
</p>

<%= link_to 'Edit', edit_tour_path(@tour) %> |
<%= link_to 'Back', tours_path %>