config/routes.rb
Rails.application.routes.draw do
  resources :user_testimonials
  resources :custom_trips
  resources :customer_msgs
  resources :tours
  resources :booking_infos
  post 'checkout/create', to: 'checkout#create'
  resources :webhooks, only: [:create]
  # post 'webhooks/create', to: 'webhooks#create'
  # post 'create' => 'checkout#create', as: :checkout_create

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root :to => 'home#landing_page'
  # =========== error pages =========================
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match "/504", to: "errors#timed_out", via: :all
  match "/422", to: "errors#unacceptable", via: :all
  # ====================================================
  get 'user_dashboard' => 'home#user_dashboard', as: :user_dashboard  
  get 'admin_dashboard' => 'home#admin_dashboard', as: :admin_dashboard
  get 'profile' => 'home#profile', as: :profile
  get 'trips_page' => 'home#trips_page', as: :trips_page
  get 'media_page' => 'home#media_page', as: :media_page
  get 'booking_form' => 'home#booking_form', as: :booking_form
  get 'booking_form2' => 'home#booking_form2', as: :booking_form2
  post 'create_booking' => 'home#create_booking', as: :create_booking
  post 'create_msg' => 'home#create_msg', as: :create_msg
  get 'payment_form' => 'booking_infos#payment_form', as: :payment_form
  get 'book_form' => 'tours#book_form', as: :book_form
  get 'postpone_booking' => 'booking_infos#postpone_booking', as: :postpone_booking
  get 'booking_details' => 'home#booking_details', as: :booking_details
  get 'checkout_page' => 'home#checkout_page', as: :checkout_page
  get 'custom_trip_form' => 'home#custom_trip_form', as: :custom_trip_form
  post 'create_custom_trip' => 'home#create_custom_trip', as: :create_custom_trip
  get 'tos' => 'home#tos', as: :tos
  get 'testimonial_form' => 'home#testimonial_form', as: :testimonial_form
  post 'create_testimonial' => 'home#create_testimonial', as: :create_testimonial
  get 'privacy_policy' => 'home#privacy_policy', as: :privacy_policy
  get 'upcoming_trips_modal' => 'home#upcoming_trips_modal', as: :upcoming_trips_modal

  get 'success_page' => 'home#success_page', as: :success_page
end

app/models/booking_info.rb
class BookingInfo < ApplicationRecord
    attr_accessor :comment

    # validates :tos_agreement, presence: true
    # validates :surname, presence: true
    # validates :othernames, presence: true
    # validates :email, presence: true
    # validates_uniqueness_of :country_desc, on: :create
    # validates :group_count, numericality: { :greater_than_or_equal_to => 1 ,message: "Please enter 1 or greater" }
end

app/controllers/booking_infos_controller.rb
class BookingInfosController < ApplicationController
  before_action :set_booking_info, only: %i[ show edit update destroy ]

  # GET /booking_infos or /booking_infos.json
  def index
    @booking_infos = BookingInfo.all
  end

  def payment_form

  end



  # GET /booking_infos/1 or /booking_infos/1.json
  def show
  end

  # GET /booking_infos/new
  def new
    @booking_info = BookingInfo.new
  end

  # GET /booking_infos/1/edit
  def edit
    @status = [["I understand and will like to postpone.","postponed"]]
  end

  # POST /booking_infos or /booking_infos.json
  def create
    @booking_info = BookingInfo.new(booking_info_params)

    respond_to do |format|
      if @booking_info.save
        BookingInfoMailer.with(booking_info: @booking_info).new_booking_info_email.deliver_later
        format.html { redirect_to root_path, notice: "Booking info was successfully created." }
        format.json { render :show, status: :created, location: @booking_info }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /booking_infos/1 or /booking_infos/1.json
  def update
    respond_to do |format|
      if @booking_info.update(booking_info_params)
        format.html { redirect_to root_path, notice: "Booking info was successfully updated." }
        format.json { render :show, status: :ok, location: @booking_info }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /booking_infos/1 or /booking_infos/1.json
  def destroy
    @booking_info.destroy
    respond_to do |format|
      format.html { redirect_to booking_infos_url, notice: "Booking info was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking_info
      @booking_info = BookingInfo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_info_params
      params.require(:booking_info).permit(:surname, :othernames, :phone_number, :coordination_preference,:group_count, :hotel_type, 
                                          :tour_duration, :purpose_statement, :user_id, :user_uid, :tour_id, :comment,:status)
    end
end

app/helpers/booking_infos_helper.rb
module BookingInfosHelper
end

app/views/booking_infos/_form.html.erb
<%= simple_form_for(@booking_info) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :surname %>
    <%= f.input :othernames %>
    <%= f.input :phone_number %>
    <%= f.input :coordination_preference %>
    <%= f.input :group_count %>
    <%= f.input :hotel_type %>
    <%= f.input :tour_duration %>
    <%= f.input :purpose_statement %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/booking_infos/_postpone_booking.html.erb
 <div id="air-mod" class="w3-modal w3-animate-opacity" style="display: block; margin-top: 50px;">
    <div class="w3-modal-content w3-card-4 " style="width: 540px; padding-bottom: 60px" >
      <div class="d-flex justify-content-end" style="padding: 10px;">
        <span onclick="document.getElementById('air-mod').style.display='none'"
            class="btn btn-lg btn-light">&times;</span>
      </div>
      <br>
      <div class="w3-container">
        <% if params[:marker] == "postponed"%>
            <div class="postponement-info text-center">
                <p class="text-4">Please contact Dr Booker on<br> +1(609)591-0060 <br>for further assistance</p>
            </div>
        <% else %>
            <%= simple_form_for(@booking_info) do |f| %>
            <%= f.error_notification %>
            <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
                <form>
                    <div class="form-inputs my-form-margin">
                        <div class="col-sm-12">
                            <div class="postponement-info text-center">
                                <p class="text-4">
                                    Please note that the amount paid for a trip is non-refundable.<br>
                                    You can only postpone to the next available tour
                                </p>
                                <span class="text-3"><b>Do you want to postpone this trip?</b></span>
                                <br><br>
                                <%= f.input :status, collection: @status, label_method: :first, value_method: :last,hint:("Please select an option from this dropdown"), input_html:{class:"form-control-lg form-select"},label:false , required: true %>
                                
                                <%# <button class="btn btn-lg btn-danger">Yes</button>
                                <button class="btn btn-lg btn-dark">No</button> %>
                            
                                <div  class="mb-3">
                                    <%= f.input :tour_id, input_html:{value:params[:tour_id],class:"form-control-lg sanbrafie-input"}, as: :hidden %>   
                                </div>
                                <div class="row mb-3">
                                    <div class="col">
                                        <%= f.input :surname, input_html:{value: current_user.surname, class:"form-control-lg sanbrafie-input"},as: :hidden %>
                                    </div>
                                    <div class="col">
                                        <%= f.input :othernames, input_html:{value: current_user.othernames, class:"form-control-lg sanbrafie-input"},as: :hidden %>
                                    </div>
                                </div>
                                <div class=" mb-3">
                                        <%= f.input :phone_number, input_html:{class:"form-control-lg sanbrafie-input"},as: :hidden %>
                                        <%= f.input :user_id, input_html:{class:"form-control-lg sanbrafie-input"},as: :hidden %>
                                        <%= f.input :user_uid, input_html:{class:"form-control-lg sanbrafie-input"},as: :hidden %>
                                        <%= f.input :email, input_html:{class:"form-control-lg sanbrafie-input"},as: :hidden %>

                                </div>
                                <div class="row mb-3">
                                    <div class="col">
                                        <%= f.input :coordination_preference, collection: @coordination_preference, label_method: :first, value_method: :last, input_html:{class:"form-control-lg sanbrafie-input"},as: :hidden %>
                                    </div>
                                    <div class="col">
                                        <%= f.input :group_count, input_html:{class:"form-control-lg sanbrafie-input"},as: :hidden%>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col">
                                        <%= f.input :hotel_type, collection: @hotel_type, label_method: :first, value_method: :last, input_html:{class:"form-control-lg sanbrafie-input"},as: :hidden %>
                                    </div>
                                    <div class="col">
                                        <%= f.input :tour_duration, input_html:{class:"form-control-lg sanbrafie-input"},as: :hidden %>
                                    </div>
                                </div>
                                <div  class="mb-3">
                                    <%= f.input :purpose_statement, collection: @purpose_statement, label_method: :first, value_method: :last, input_html:{class:"form-control-lg sanbrafie-input"},as: :hidden %>
                                    <br>
                                    <%= f.input :comment, as: :text, input_html:{class:"form-control-lg sanbrafie-input"}, placeholder:"Add a little detail to your purpose statement",label:false,as: :hidden %>
                                </div>
                                
                                <%# <br> %>
                                <div class="row">
                                    <div class="col-sm-6 d-grid">
                                        <%= f.submit "Postpone", class: "btn btn-lg btn-danger" %>
                                    </div>
                                    <div class="col-sm-6 d-grid">
                                        <span onclick="document.getElementById('air-mod').style.display='none'" class="btn btn-lg btn-dark">No</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            <% end %>
        <% end %>
      </div>
    </div>
</div>

<style>
.w3-modal{
    z-index: 999 !important;
}
    .sanbrafie-input{
        background-color:#f2f2f2  !important;
        border:none !important;
        border-radius: 0px !important;
    }
    .my-form-margin{
        padding: 0 40px;
    }
    .postponement-info{
        padding: 25px;
        background-color:#dfe6e9;
    }
</style>

app/views/booking_infos/edit.html.erb
<h1>Editing Booking Info</h1>

<%= render 'form', booking_info: @booking_info %>

<%= link_to 'Show', @booking_info %> |
<%= link_to 'Back', booking_infos_path %>

app/views/booking_infos/edit.js.erb
$('.booking-edit').html("<%= escape_javascript(render 'postpone_booking')%>")

app/views/booking_infos/index.html.erb
<div class="page-topic text-center">
    <h2> Booking Information </h2>
</div>
<div class="my-content"> 
    <div class="shadow-box-no-border">
        <hr/>
        <div>
            <button class="btn btn-outline-primary">Download CSV  <i class="fa fa-download"></i></button>
            <button class="btn btn-outline-primary">Search  <i class="fa fa-search"></i></button>

            <%= link_to new_booking_info_path, class:"btn btn-outline-primary float-right" do %>
                <span class="glyphicon glyphicon-plus"></span>
                New Booking
            <% end %>
        </div>
    

        <div class="table-responsive">
        <hr/>
            <table class="table table-striped table-hover">
                <thead class="bg-light">
                <tr>
                    <th>#</th>
                                        <th>Surname</th>
                                        <th>Othernames</th>
                                        <th>Phone number</th>
                                        <th>Coordination preference</th>
                                        <th>Group count</th>
                                        <th>Hotel type</th>
                                        <th>Tour duration</th>
                                        <th>Purpose statement</th>
                                        <th colspan="3"></th>
                </tr>
                </thead>

                <tbody>
                <% @booking_infos.each_with_index do |booking_info, index| %>
                    <tr>
                        <td><%= index + 1 %></td>
                                        <td><%= booking_info.surname %></td>
                                        <td><%= booking_info.othernames %></td>
                                        <td><%= booking_info.phone_number %></td>
                                        <td><%= booking_info.coordination_preference %></td>
                                        <td><%= booking_info.group_count %></td>
                                        <td><%= booking_info.hotel_type %></td>
                                        <td><%= booking_info.tour_duration %></td>
                                        <td><%= booking_info.purpose_statement %></td>
                           
                        <td>
                            <%= link_to booking_info, class:"btn btn-md btn-outline-primary",remote: true do %>
                                Details
                            <% end %>
                        </td>                 
                        <td>
                            <%= link_to edit_booking_info_path(booking_info), class:"btn btn-md btn-secondary" do %>
                                <i class="fa fa-edit"></i>
                            <% end %>
                        </td>
                        <td>
                            <%= link_to  booking_info, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-md btn-danger" do %>
                                <i class="fa fa-trash"></i>
                            <% end %>
                        </td>
                    
                    </tr>
                <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/booking_infos/new.html.erb
<h1>New Booking Info</h1>

<%= render 'form', booking_info: @booking_info %>

<%= link_to 'Back', booking_infos_path %>

app/views/booking_infos/payment_form.html.erb
<div class="page-topic text-center">
    <h4>Payment Form</h4>
</div>
<div class="my-content">
    <br>
    <div class="shadow-box-no-border">
        <div class="text-center">
            <h3>Thanks for booking <%= params[:tour_name] %> with us!</h3>
            <h5>We look forward lorem ipsum dolor </h5>
        </div>
    </div>
</div>

app/views/booking_infos/postpone_booking.js.erb
$('#postpone').html("<%= escape_javascript(render 'postpone_booking')%>")

app/views/booking_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Surname:</strong>
  <%= @booking_info.surname %>
</p>

<p>
  <strong>Othernames:</strong>
  <%= @booking_info.othernames %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @booking_info.phone_number %>
</p>

<p>
  <strong>Coordination preference:</strong>
  <%= @booking_info.coordination_preference %>
</p>

<p>
  <strong>Group count:</strong>
  <%= @booking_info.group_count %>
</p>

<p>
  <strong>Hotel type:</strong>
  <%= @booking_info.hotel_type %>
</p>

<p>
  <strong>Tour duration:</strong>
  <%= @booking_info.tour_duration %>
</p>

<p>
  <strong>Purpose statement:</strong>
  <%= @booking_info.purpose_statement %>
</p>

<%= link_to 'Edit', edit_booking_info_path(@booking_info) %> |
<%= link_to 'Back', booking_infos_path %>