config/routes.rb
Rails.application.routes.draw do
  resources :user_testimonials
  resources :custom_trips
  resources :customer_msgs
  resources :tours
  resources :booking_infos
  post 'checkout/create', to: 'checkout#create'
  resources :webhooks, only: [:create]
  # post 'webhooks/create', to: 'webhooks#create'
  # post 'create' => 'checkout#create', as: :checkout_create

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root :to => 'home#landing_page'
  # =========== error pages =========================
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match "/504", to: "errors#timed_out", via: :all
  match "/422", to: "errors#unacceptable", via: :all
  # ====================================================
  get 'user_dashboard' => 'home#user_dashboard', as: :user_dashboard  
  get 'admin_dashboard' => 'home#admin_dashboard', as: :admin_dashboard
  get 'profile' => 'home#profile', as: :profile
  get 'trips_page' => 'home#trips_page', as: :trips_page
  get 'media_page' => 'home#media_page', as: :media_page
  get 'booking_form' => 'home#booking_form', as: :booking_form
  get 'booking_form2' => 'home#booking_form2', as: :booking_form2
  post 'create_booking' => 'home#create_booking', as: :create_booking
  post 'create_msg' => 'home#create_msg', as: :create_msg
  get 'payment_form' => 'booking_infos#payment_form', as: :payment_form
  get 'book_form' => 'tours#book_form', as: :book_form
  get 'postpone_booking' => 'booking_infos#postpone_booking', as: :postpone_booking
  get 'booking_details' => 'home#booking_details', as: :booking_details
  get 'checkout_page' => 'home#checkout_page', as: :checkout_page
  get 'custom_trip_form' => 'home#custom_trip_form', as: :custom_trip_form
  post 'create_custom_trip' => 'home#create_custom_trip', as: :create_custom_trip
  get 'tos' => 'home#tos', as: :tos
  get 'testimonial_form' => 'home#testimonial_form', as: :testimonial_form
  post 'create_testimonial' => 'home#create_testimonial', as: :create_testimonial
  get 'privacy_policy' => 'home#privacy_policy', as: :privacy_policy
  get 'upcoming_trips_modal' => 'home#upcoming_trips_modal', as: :upcoming_trips_modal

  get 'success_page' => 'home#success_page', as: :success_page
end

app/views/layouts/_footer.html.erb
<footer class="my-footer">

</footer>

<style>
    .my-footer{
        background: #181818;
        
    }
</style>

app/views/layouts/_messages.html.erb
<% if user_signed_in? %>
    <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div id="sys-msg" class="w3-modal w3-animate-opacity" style="display: block; margin-top: 50px; ">
            <div class="w3-modal-content w3-card-4 " style="width: 400px; padding-bottom:20px; height: 190px !important;" >
                <div class="d-flex justify-content-end" style="padding: 10px;">
                    <span onclick="document.getElementById('sys-msg').style.display='none'"
                        class="btn btn-md btn-light">&#10799;</span>
                </div>
                <div class="w3-container text-center" style="padding:-30px 10px 10px 10px;">
                    <% if name.to_s == 'notice'%>
                        <div class="alert alert-success" role="alert" id="flash">
                            <!--<div class="alert alert-<%#= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert" id="flash">-->
                            <%# <button type="button" class=" btn-close" data-dismiss="alert" aria-hidden="true"></button> %>
                            <i class="fas fa-check-circle fa-2x"></i> <%= content_tag :div, msg, :id => "flash_#{name}" %>
                        </div>
                    <% else %>
                        <div class="alert alert-danger" role="alert" id="flash">
                            <%# <button type="button" class=" btn-close" data-dismiss="alert" aria-hidden="true"></button> %>
                            <i class="fas fa-times-circle fa-2x"></i> <%= content_tag :div, msg, :id => "flash_#{name}" %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    <% end %>
<% end %>
<%# &times; %>

<style>
    .flash{
        background-color: #fff !important;
       
    }
    .alert{
        background-color: #fff !important;
        z-index: 100;
    }
    .alert-success{
        background-color: #fff !important;
        border-color: #fff !important;
        color: #4bb543 !important;
         font-size: 18px !important;
        font-weight: 600 !important;
    }
    .alert-danger{
        background-color: #fff !important;
        border-color: #fff !important;
        color: #ff8080 !important;
    }
     

</style>

<script type="text/javascript">
    $(document).ready(function(){
        setTimeout(function(){
            $('#sys-msg').remove();
        }, 3200);
    })
</script>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar fixed-top navbar-expand-md navbar-light bg-white col-12 shadow-sm" >
  <div class="container-fluid" id="navbar-example">
    <% if !user_signed_in? %>
      <a class="navbar-brand" href="/">
        <img src="<%= asset_pack_path 'media/images/logo.png' %>" height="50px" width="80" alt="Sanbrafie logo">
      </a>
    <% else %>
      <a class="navbar-brand" href="/user_dashboard"> 
        <img src="<%= asset_pack_path 'media/images/logo.png' %>" height="50px" width="80" alt="Sanbrafie logo">
      </a>
    <% end %>
    <p id="navbar-head-text">Sanbrafie Group Inc</p>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if !user_signed_in? %>
          <li class="nav-item active">
            <a class="nav-link my-routes active" href="/">HOME</a>
          </li>
          <li class="nav-item " id="destination-btn">
            <a class="nav-link my-routes" href="#destinations" >TRIPS</a>
          </li>
          <li class="nav-item">
            <a class="nav-link my-routes" href="#testimonials">TESTIMONIALS</a>
          </li>
          <li class="nav-item">
            <a class="nav-link my-routes" href="#about">ABOUT US</a>
          </li>
          <li class="nav-item">
            <a class="nav-link my-routes" href="#contact">CONTACT US</a>
          </li>
           
        <% else %>
          <li class="nav-item">
           <%#= current_user.stripe_customer_id %>
          </li>
          <li class="nav-item">
            <a class="nav-link my-routes active" href="/">DASHBOARD</a>
          </li>
        <% end %>
      </ul>
      <div class="d-flex">
        <% if user_signed_in? %>
          <%= link_to "Logout", destroy_user_session_path , :method=> 'delete',class: "btn btn-lg btn-outline-dark nav-buttons me-auto"  %>
        <% else %>
          <%= link_to "Login", new_user_session_path ,class: "btn btn-lg btn-outline-dark nav-buttons me-auto"  %>
          <%= link_to 'Travel with us', booking_form_path, remote:true, class:"btn btn-lg btn-dark nav-buttons  me-auto"%>
          <%# ,style:"background: #FBC71D !important; "  %>
        <% end %>
      </div>
    </div>
  </div>
</nav>
<style>
  .bg-darkk{
    background-color: #101010 !important;
  }
   .bg-white{
    background-color: #f5f8f9 !important;
  }
  .active-border{
    border-bottom: 2px solid #202020;
  }

</style>
<script>
  var scrollSpy = new bootstrap.ScrollSpy(document.body, {
    target: '#navbar-example'
  })
  console.log("00000000")
 
</script>

app/views/layouts/_navigation.html.erb
<nav class="navbar fixed-top navbar-expand-md navbar-light bg-white col-12" >
  <div class="container-fluid" id="navbar-example">
    <% if !user_signed_in? %>
      <a class="navbar-brand" href="/">
        <img src="<%= asset_pack_path 'media/images/logo.png' %>" height="50px" width="80" alt="Sanbrafie logo">
      </a>
    <% else %>
      <a class="navbar-brand" href="/user_dashboard"> 
        <img src="<%= asset_pack_path 'media/images/logo.png' %>" height="50px" width="80" alt="Sanbrafie logo">
      </a>
    <% end %>
    <p id="navbar-head-text">Sanbrafie Group Inc</p>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if !user_signed_in? %>
          <li class="nav-item active">
            <a class="nav-link my-routes active" href="/">HOME</a>
          </li>
          <li class="nav-item " id="destination-btn">
            <a class="nav-link my-routes" href="#destinations" >TRIPS</a>
          </li>
          <li class="nav-item">
            <a class="nav-link my-routes" href="#testimonials">TESTIMONIALS</a>
          </li>
          <li class="nav-item">
            <a class="nav-link my-routes" href="#about">ABOUT US</a>
          </li>
          <li class="nav-item">
            <a class="nav-link my-routes" href="#contact">CONTACT US</a>
          </li>
           
        <% else %>
          <li class="nav-item">
           <%#= current_user.stripe_customer_id %>
          </li>
          <li class="nav-item">
            <a class="nav-link my-routes active" href="/">DASHBOARD</a>
          </li>
        <% end %>
      </ul>
      <div class="d-flex">
        <% if user_signed_in? %>
          <%= link_to "Logout", destroy_user_session_path , :method=> 'delete',class: "btn btn-lg btn-outline-dark nav-buttons me-auto"  %>
        <% else %>
          <%= link_to "Login", new_user_session_path ,class: "btn btn-lg btn-outline-dark nav-buttons me-auto"  %> <!--#FBC71D-->
          <%= link_to 'Travel with us', booking_form_path, remote:true, class:"btn btn-lg btn-dark nav-buttons  me-auto",style:"background-color: #090909 !important; border-color:#090909 !important;" %>
        <% end %>
      </div>
    </div>
  </div>
</nav>
<style>
  .bg-darkk{
    background-color: #101010 !important;
  }
   .bg-white{
    background-color: #FCEED8 !important;
  }
  .active-border{
    border-bottom: 2px solid #202020;
  }
  .my-routes{
    font-family:  'Montserrat'!important;
    font-weight: 600 !important;
    font-size: 13px !important;
    /* color: #f5f5f7 !important; */
    color: #010101 !important;
  }
</style>
<script>
  var scrollSpy = new bootstrap.ScrollSpy(document.body, {
    target: '#navbar-example'
  })
  console.log("00000000")
 
</script>

app/views/layouts/_sidenav.html.erb
<div class="container-fluid">
<% if user_signed_in? %>
    <div class="row flex-nowrap">
        <div class="col-auto col-md-2 col-xl-2 px-sm-2 px-0 bg-light">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2  min-vh-100">
                <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto  text-decoration-none">
                    <span class="fs-5 d-none d-sm-inline">Menu</span>
                </a>
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                    <li class="nav-item">
                        <%= link_to 'Profile', profile_path, class:" " %>
                    </li>
                    <li class="nav-item">
                       <%= link_to 'My Gallery',media_page_path, class:" " %>
                    </li>
                    <li class="nav-item">
                        <%= link_to 'My trips', trips_page_path, class:" " %>
                    </li>
                </ul>
                <hr>
            </div>
        </div>
        <% end %>
        <div class="col py-3">
            <%= render 'layouts/navigation'%>
            <div id="notif-msg" class="col-sm-12">
            <%= render 'layouts/messages' %>
            </div>
            <br>
            <%= yield %>
        </div>
    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sanbrafie</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_pack_tag 'fav.png' %>
   <script src="https://js.stripe.com/v3/"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Tangerine&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Zen+Antique&display=swap" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag Ckeditor.cdn_url %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>
    <br><br><br>
    <div class="row" style="margin-top: -10px;">
      <div id="notif-msg" class="col-sm-12">
        <%= render 'layouts/messages' %>
      </div>
      <%= yield %>
    </div>
  </body>
 
</html>

<style>
body {
  position: relative;
}
</style>
<script>
  var scrollSpy = new bootstrap.ScrollSpy(document.body, {
  target: '#navbar-example'
})
</script>